### ISSUE TITLE
Flatpak installer

### ISSUE THREAD

**Issue by romeo-07** [refi64/flatpak-presentation#1]
Nice documentation and video though you tlp and then the back and forth flipping of the screen making the presentation more difficult to absorb.  slow the typing, side by side presentation material with demo, increase font size of typed text.

- I installed gulp (though apparently with issues on Mint 19.2)
-node.js
-yarn (when trying just to run using yarn it complains needing a scenario)

Gulp installation issues...maybe opportunity to create a flatpak for documentation.

$ gulp
module.js:549
    throw err;
    ^

Error: Cannot find module '@marp-team/marpit'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/romeo0/flatpak-presentation/gulpfile.js:2:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by refi64** [comment]
Did you try running `yarn install`? Seems like some dependencies are missing.

Also thanks for watching! I can't really fit the presentation side by side because my laptop monitor isn't really big enough for that though, which is also why the font size is a tad small. I'll look into tweaking it next time, though!
